---
- name: k8s | set variables
  ansible.builtin.include_vars: '{{ item }}'
  tags:
    - k8s
  with_first_found:
    - default.yml

- name: k8s
  ansible.builtin.include_tasks: kubernetes.yml
  tags:
    - k8s

- name: k8s | flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - k8s
