---
- name: Docker | install docker key
  ansible.builtin.copy:
    src: usr/share/keyrings/docker.gpg
    dest: /usr/share/keyrings/docker.gpg
    owner: root
    group: root
    mode: '0644'
  tags:
    - docker

- name: Docker | add docker repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ debian_version }} stable
    state: present
    filename: docker
  tags:
    - docker

- name: ContainerD | install docker engine packages
  ansible.builtin.package:
    pkg: '{{ item }}'
    state: present
  loop: '{{ docker_engine_packages_list }}'
  tags:
    - docker

- name: ContainerD | configure /etc/containerd/config.toml
  ansible.builtin.copy:
    src: etc/containerd/config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  notify: restart containerd
  tags:
    - docker
