apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 172.25.0.201
  share: /mnt/user/k8s
reclaimPolicy: Retain
volumeBindingMode: Immediate
